### ISSUE TITLE
Union set operator used on dicts raises TypeError

### ISSUE THREAD

**Issue by sqqqrly** [preludeorg/vertebrae#43]
Running the sample, I get an unexpected 500:
```╰─➤  python server.py
2022-12-30 15:17:49 - INFO  [vertebrae.server/core.py] Serving 1 apps with 1 services
2022-12-30 15:17:58 - ERROR [vertebrae.api/authentication.py] [API] Unauthorized request
2022-12-30 15:18:05 - ERROR [aiohttp.server/web_protocol.py] Error handling request
Traceback (most recent call last):
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/authentication.py", line 18, in helper
    params['data'] = await strip_request(request=args[1])
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/vertebrae/core.py", line 26, in strip_request
    data = dict(request.match_info) | dict(request.rel_url.query)
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

When I look at core.py +26, I see it is using a union set operator on dicts. I do not think this supported:
```
╰─➤  python
Python 3.8.13 (default, Apr 19 2022, 00:53:22)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> l1 = [1,2,3]
>>> l2 = [7,8,9]
>>> l1 |l2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'list' and 'list'

>>> d1 = {"a":1}
>>> d2 = {"b":2}
>>> d1|d2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

>>> s1 = {1,2,3}
>>> s2 = {3,4,5}
>>> s1|s2
{1, 2, 3, 4, 5}
```
So sets work, but lists and dicts do not.  Am I doing something wrong?  I hit the server with:
```
╰─➤  curl -X GET "localhost:8079/chat" -H 'Content-Type: application/json' -H "token: abc123"
500 Internal Server Error

Server got itself in trouble%```

**Comment by privateducky** [comment]
Ah, I think the merge of dict syntax we're using here (dict | dict) was added to Python in version 3.9 and it looks like you're on 3.8. That should be the only syntax in this project that is above 3.7 - so we can patch that to make it work for you.

**Comment by sqqqrly** [comment]
Great. 

I changed my curl to `curl -X GET "localhost:8079/chat" -H 'Content-Type: text/plain' -H "token: abc123"` so that I do not end up in the else-case.

```
╰─➤  python server.py
2022-12-30 15:37:20 - INFO  [vertebrae.server/core.py] Serving 1 apps with 1 services
2022-12-30 15:37:24 - DEBUG [vertebrae.chat/chat.py] Retrieving messages
2022-12-30 15:37:24 - ERROR [aiohttp.server/web_protocol.py] Error handling request
Traceback (most recent call last):
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aioredis/connection.py", line 692, in connect
    await self._connect()
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aioredis/connection.py", line 719, in _connect
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/authentication.py", line 19, in helper
    return await func(args[0], **params)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/routes/core_routes.py", line 18, in _get_messages
    messages = await Service.find('chat').get_msgs()
  File "/home/dohlemacher/cloud/vertebrae/sample/app/services/chat.py", line 19, in get_msgs
    messages = await self.cache.get_del('voicemail')
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/vertebrae/stores/cache.py", line 27, in get_del
    return await self._cache.execute_command('GETDEL', k)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aioredis/client.py", line 1082, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aioredis/connection.py", line 1416, in get_connection
    await connection.connect()
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aioredis/connection.py", line 698, in connect
    raise ConnectionError(self._error_message(e))
aioredis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. 111.
```

**Comment by sqqqrly** [comment]
```

**Comment by privateducky** [comment]
Great. This error would indicate you're not running Redis. If you're testing out the sample app, you'll want to start a Redis instance on the same machine.

**Comment by sqqqrly** [comment]
Thanks, redis installed.  Missed that in the README.

**Comment by sqqqrly** [comment]
with redis available:
```
╰─➤  python server.py
2022-12-30 16:01:09 - INFO  [vertebrae.server/core.py] Serving 1 apps with 1 services
2022-12-30 16:01:12 - ERROR [aiohttp.server/web_protocol.py] Error handling request
Traceback (most recent call last):
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/authentication.py", line 19, in helper
    return await func(args[0], **params)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/routes/core_routes.py", line 23, in _save_message
    await Service.find('chat').save_msg(msg=data.get('text'))
AttributeError: 'str' object has no attribute 'get'```

**Comment by sqqqrly** [comment]
With redis available:
```
╰─➤  curl -X POST "localhost:8079/chat" -H 'Content-Type: text/plain' -H "token: abc123" -d '{"text":"hi, there"}'
500 Internal Server Error

Server got itself in trouble% 
```
```
╰─➤  python server.py
2022-12-30 16:01:09 - INFO  [vertebrae.server/core.py] Serving 1 apps with 1 services
2022-12-30 16:01:12 - ERROR [aiohttp.server/web_protocol.py] Error handling request
Traceback (most recent call last):
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/dohlemacher/cloud/imx-performance-alerting-tool/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/authentication.py", line 19, in helper
    return await func(args[0], **params)
  File "/home/dohlemacher/cloud/vertebrae/sample/app/routes/core_routes.py", line 23, in _save_message
    await Service.find('chat').save_msg(msg=data.get('text'))
AttributeError: 'str' object has no attribute 'get'
```

**Comment by khyberspache** [comment]
Try with this:
```
curl -X POST "localhost:8079/chat" -H 'Content-Type: application/json' -H "token: abc123" -d '{"text":"hi, there"}'
```

**Comment by privateducky** [comment]
@sqqqrly all work?

**Comment by mireaulf** [comment]
Closing. Please re-open if needed.
